"""add to model User column confirmed

Revision ID: 4be010cce40a
Revises: 4a62b0d78a8c
Create Date: 2023-08-07 20:13:16.952050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4be010cce40a'
down_revision = '4a62b0d78a8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'moderator', 'user', name='role'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'moderator', 'user', name='role'),
               nullable=True)
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
