"""remove unique title

Revision ID: 8b9455235e9e
Revises: a7e1c95d2f58
Create Date: 2023-07-31 21:43:18.919453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9455235e9e'
down_revision = 'a7e1c95d2f58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todos_title', table_name='todos')
    op.create_index(op.f('ix_todos_title'), 'todos', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_title'), table_name='todos')
    op.create_index('ix_todos_title', 'todos', ['title'], unique=False)
    # ### end Alembic commands ###
