# Generated by Django 4.2.3 on 2023-07-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("completed", models.BooleanField(default=False)),
                ("published", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["published"],
            },
        ),
    ]
