# Generated by Django 4.2.3 on 2023-07-13 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photo_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("photo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="path",
            field=models.ImageField(
                upload_to=photo_app.models.upload_image,
                validators=[photo_app.models.validate_file_size],
            ),
        ),
    ]
